### ISSUE TITLE
Info on usage or missing element

### ISSUE THREAD

**Issue by docop** [TabulateJarl8/screen-brightness#1]
Hi  This look quite interesting and could be quite easy to run and use. Actually, is there something else required to adjust X11 ?  As on arch with a vga out, it do run, but while it said :  setting brightness to 0.3 , it don't do change anything.
 Try over rdp , xrdp. The display is detected, but changing did not happen after hitting save.

Thanks

**Comment by TabulateJarl8** [comment]
`xrandr` should be the only requirement. If you run `xrandr --output YOUR_DEVICE --brightness 0.3` manually does it work?

**Comment by docop** [comment]
all good, look it was the hp system that don't take up any adjustment. thanks
